// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image7":
            case "undefined":return img`
2 2 2 . . . . . . . . . . 2 2 2 
2 2 2 2 . . . . . . . . 2 2 2 2 
2 2 2 2 2 . . . . . . 2 2 2 2 2 
. 2 2 2 2 2 . . . . 2 2 2 2 2 . 
. . 2 2 2 2 2 . . 2 2 2 2 2 . . 
. . . 2 2 2 2 2 2 2 2 2 2 . . . 
. . . . 2 2 2 2 2 2 2 2 . . . . 
. . . . . 2 2 2 2 2 2 . . . . . 
. . . . . 2 2 2 2 2 2 . . . . . 
. . . . 2 2 2 2 2 2 2 2 . . . . 
. . . 2 2 2 2 2 2 2 2 2 2 . . . 
. . 2 2 2 2 2 . . 2 2 2 2 2 . . 
. 2 2 2 2 2 . . . . 2 2 2 2 2 . 
2 2 2 2 2 . . . . . . 2 2 2 2 2 
2 2 2 2 . . . . . . . . 2 2 2 2 
2 2 2 . . . . . . . . . . 2 2 2 
`;
            case "image5":
            case "Vpipe":return img`
. c c c c c c . 
c b f f f f b c 
. c b f f b c . 
. . c b b c . . 
. . c b b c . . 
. . c b b c . . 
. . c b b c . . 
. . c b b c . . 
. . c b b c . . 
. . c b b c . . 
. . c b b c . . 
. c c b b c c . 
. c b b b b c . 
. c b b b b c . 
. c b b b b c . 
`;
            case "image6":
            case "Springboard":return img`
. . . . . . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . . . . . 
. . . . . a . . . . . . . . . . . . . . 
. . . . . a a . . . . . . . a . . . . . 
. . . . . . . a . . . . a a . . . . . . 
. . . . . . a . a a a a . . . . . . . . 
. . . . . . . a . . . . a . . . . . . . 
. . . . . . . . a a a a . . . . . . . . 
. . . . . . . a . . . . . . . . . . . . 
. . . . . . . . a a a . . . . . . . . . 
. b b b b b b b b b b b b b b b b b . . 
b d d d d c d d c c c c c c c c c c b b 
b c c c c c c c c c c c c c c c c c c b 
b c c c c c c c c c c c c c c c c c c b 
. b b b b b b b b b b b b b b b b b b . 
`;
            case "image4":
            case "Hpipe":return img`
. b b b b b b b b b b b b b b b b b b b b b b b b b b b . . 
b d d d d d d d c c c d d d c c c c c c c c c c c c c c b b 
b c c c c c c c c c c c c c c c c c c c c c c c c c c c c b 
b c c c c c c c c c c c c c c c c c c c c c c c c c c c c b 
. b b b b b b b b b b b b b b b b b b b b b b b b b b b b . 
`;
            case "o-X5w{]fF%)X*`[vP{23":
            case "player_gun1":return img`
................
................
....111.........
....11f.........
....11f.........
....111...aaaaaa
...6f666666ffffa
...6f666666faaaa
...6fff...aaa...
...6fff.........
...6fff.........
...6fff.........
....aad.........
....aad.........
....aad.........
....aad.........
....aad.........
....aad.........
................
................
`;
            case "image2":
            case "player_sword1":return img`
................
...........b....
....eeee...b....
....e..e...b....
....e..e...b....
....eeee...b....
....822222424...
...482....2e....
...48222222e....
..4.8..8........
..4.8..8........
..448888........
....7.76........
....7.76........
....7.76........
....7.7.6.......
....77766.......
................
................
................
`;
            case "image1":
            case "player_sword":return img`
................
...........9....
....111....9....
....11f....9....
....11f....9....
....111....6....
...6f6666661....
...6f6666661....
...6fff.........
...6fff.........
...6fff.........
...6fff.........
....aad.........
....aad.........
....aad.........
....aad.........
....aad.........
....aad.........
................
................
`;
            case "image3":
            case "player_swordlifesteal":return img`
................
..........2222..
....eee..222222.
....eef....e.222
....eef....e...2
....eee....e....
...4f444444e....
...4f444444e....
...4fff....e....
...4fff....e....
...4fff....e....
...4fff....e....
....ee3....e....
....ee3....e....
....ee3....e....
....ee3....e....
....ee3.........
....ee3.........
................
................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
