// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "player_gun2":return img`
................
................
....eeee........
....e..e........
....e..e........
....eeee...bbbb.
....822222b....b
...482....b.bbb.
...48222222b....
...48..8........
...48..8........
...48888........
....7.76........
....7.76........
....7.76........
....7.76........
....7776........
................
................
................
`;
            case "image3":
            case "player_sword2":return img`
................
...........b....
....eeee...b....
....e..e...b....
....e..e...b....
....eeee...b....
....822222424...
...482....2e....
...48222222e....
..4.8..8........
..4.8..8........
..448888........
....7.76........
...7..76........
..7..7.6........
.7..76.6........
.777.666........
................
................
................
`;
            case "o-X5w{]fF%)X*`[vP{23":
            case "player_gun1":return img`
................
................
....eeee........
....e..e........
....e..e........
....eeee...bbbb.
....822222b....b
...482....b.bbb.
...48222222b....
..4.8..8........
..4.8..8........
..448888........
....7.76........
....7.76........
....7.76........
....7.7.6.......
....77766.......
................
................
................
`;
            case "image2":
            case "player_sword1":return img`
................
...........b....
....eeee...b....
....e..e...b....
....e..e...b....
....eeee...b....
....822222424...
...482....2e....
...48222222e....
..4.8..8........
..4.8..8........
..448888........
....7.76........
....7.76........
....7.76........
....7.7.6.......
....77766.......
................
................
................
`;
            case "image7":
            case "undefined":return img`
2 2 2 . . . . . . . . . . 2 2 2 
2 2 2 2 . . . . . . . . 2 2 2 2 
2 2 2 2 2 . . . . . . 2 2 2 2 2 
. 2 2 2 2 2 . . . . 2 2 2 2 2 . 
. . 2 2 2 2 2 . . 2 2 2 2 2 . . 
. . . 2 2 2 2 2 2 2 2 2 2 . . . 
. . . . 2 2 2 2 2 2 2 2 . . . . 
. . . . . 2 2 2 2 2 2 . . . . . 
. . . . . 2 2 2 2 2 2 . . . . . 
. . . . 2 2 2 2 2 2 2 2 . . . . 
. . . 2 2 2 2 2 2 2 2 2 2 . . . 
. . 2 2 2 2 2 . . 2 2 2 2 2 . . 
. 2 2 2 2 2 . . . . 2 2 2 2 2 . 
2 2 2 2 2 . . . . . . 2 2 2 2 2 
2 2 2 2 . . . . . . . . 2 2 2 2 
2 2 2 . . . . . . . . . . 2 2 2 
`;
            case "image5":
            case "Vpipe":return img`
. c c c c c c . 
c b f f f f b c 
. c b f f b c . 
. . c b b c . . 
. . c b b c . . 
. . c b b c . . 
. . c b b c . . 
. . c b b c . . 
. . c b b c . . 
. . c b b c . . 
. . c b b c . . 
. c c b b c c . 
. c b b b b c . 
. c b b b b c . 
. c b b b b c . 
`;
            case "image6":
            case "Springboard":return img`
. . . . . . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . . . . . 
. . . . . a . . . . . . . . . . . . . . 
. . . . . a a . . . . . . . a . . . . . 
. . . . . . . a . . . . a a . . . . . . 
. . . . . . a . a a a a . . . . . . . . 
. . . . . . . a . . . . a . . . . . . . 
. . . . . . . . a a a a . . . . . . . . 
. . . . . . . a . . . . . . . . . . . . 
. . . . . . . . a a a . . . . . . . . . 
. b b b b b b b b b b b b b b b b b . . 
b d d d d c d d c c c c c c c c c c b b 
b c c c c c c c c c c c c c c c c c c b 
b c c c c c c c c c c c c c c c c c c b 
. b b b b b b b b b b b b b b b b b b . 
`;
            case "image4":
            case "Hpipe":return img`
. b b b b b b b b b b b b b b b b b . . 
b d d d d c d d c c c c c c c c c c b b 
b c c c c c c c c c c c c c c c c c c b 
b c c c c c c c c c c c c c c c c c c b 
. b b b b b b b b b b b b b b b b b b . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
